export default {
    'day_1': '基础类型',
    'day_2': '面向对象概念',
    'day_3': '简单内存模型',
    'day_4': '面对对象进阶',
    'day_5': '封装和多态',
    'day_6': '抽象',
    'day_7': '基础知识补充',
    'day_8': '集合基础',
    'day_9': '集合体系抽象类',
    'day_10': 'ArrayList',
    'day_11': '泛型',
    'day_12': 'sort',
    'day_13': 'HashMap使用',
    'day_14': '实现一个HashMap',
    'day_15': 'HashMap源码',
    'day_16': 'HashSet',
    'day_17': '异常处理机制',
    'day_18': '注解与反射',
    'day_19': 'Servlet',
    'day_20': 'Maven',
    'day_21': 'Servlet生命周期',
    'day_22': 'HttpServlet',
    'day_23': 'Cookie',
    'day_24': 'Servlet Filter',
    'day_25': 'Servlet Listener',
    'day_26': 'Servlet 注解式开发',
    'day_27': 'MySQL 基础操作',
    'day_28': '索引',
    'day_29': '事务基础',
    'day_30': 'JDBC',
    'day_31': 'Maven补充'
}
  